### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by paulshryock** [cferdinandi/gmt-automated-slack-invites#2]
I installed this plugin, placed the shortcode into a page and published the page. Viewing the page, I filled out the email address field and hit the submit button, and that resulted in this error message:

![screen shot 2017-04-21 at 1 15 03 pm](https://cloud.githubusercontent.com/assets/7530507/25293259/00f70500-26a8-11e7-99e0-485e4da18f3c.png)

Any idea how to fix this problem?

**Comment by cferdinandi** [comment]
Do you have a demo site I can look at?

**Comment by paulshryock** [comment]
https://pshry.com/slack-team-signup/

**Comment by cferdinandi** [comment]
It looks like you're using an incorrect team name for your Slack community. Should not have spaces. See this thread (for the plugin I pulled the Slack API stuff from) for more details: https://github.com/rtCamp/automate-slack-invite-gravityforms/issues/8
