### ISSUE TITLE
Cannot activate the plugin

### ISSUE THREAD

**Issue by randomsuffer** [cferdinandi/gmt-automated-slack-invites#3]
I uploaded the plugin as usual, here's an error i get when trying to activate it in WordPress.
`Fatal error: Can't use function return value in write context in /www/mysite.com/wp-content/plugins/gmt-automated-slack-invites-master/includes/helpers.php on line 149`

**Comment by cferdinandi** [comment]
What version of PHP are you running? Looks like this may be a pre-5.5 issue.

**Comment by randomsuffer** [comment]
Oh, sure, I had 5.3 version.
Switched to 7.1 and everything works fine!
Thank you very much for such a quick response!

**Comment by cferdinandi** [comment]
I'm actually going to reopen this one as a reminder to myself to update the docs to indicate the minimum version required. Thanks!

**Comment by haxxus** [comment]
Hello , I'm getting 

Request failed. Array

After pressing Join button ,Could i have entered something incorrectly? I'm using updated wordpress and php 7.0

**Comment by cferdinandi** [comment]
Have you added a Slack channel and API key to the settings?

**Comment by haxxus** [comment]
The slack channel goes in Team name ?

**Comment by haxxus** [comment]
ah ok , yes i had .slack.com in it , removed it and now is working nicely

**Comment by haxxus** [comment]
this invite system works infinite ? or does it need to be recreated after so many users join from it

**Comment by cferdinandi** [comment]
Works forever. It uses the Slack API.

**Comment by cferdinandi** [comment]
PHP version requirements Added to readme
